import { Priority } from '../modules/tasks/dto/Create-Tasks.dto';

export const seedUsers = [
    { seedRef: 1, username: 'alice', email: 'alice@test.com', password: 'password123' },
    { seedRef: 2, username: 'bob', email: 'bob@test.com', password: 'password123' },
    { seedRef: 3, username: 'charlie', email: 'charlie@test.com', password: 'password123' },
    { seedRef: 4, username: 'diana', email: 'diana@test.com', password: 'password123' },
];

export const seedTasks = [
    {
        title: 'Buy groceries',
        description: 'Milk, eggs, bread',
        completed: false,
        priority: Priority.LOW,
        user_id: 1,
    },
    {
        title: 'Finish report',
        description: 'Q3 summary',
        completed: true,
        priority: Priority.HIGH,
        user_id: 1,
    },
    {
        title: 'Review pull requests',
        description: 'Check open PRs on GitHub',
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 1,
    },
    {
        title: 'Schedule team meeting',
        description: 'Sync on sprint goals',
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 1,
    },
    {
        title: 'Call dentist',
        description: undefined,
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 2,
    },
    {
        title: 'Plan weekend trip',
        description: 'Book hotel and train tickets',
        completed: false,
        priority: Priority.LOW,
        user_id: 2,
    },
    {
        title: 'Update resume',
        description: 'Add recent projects',
        completed: true,
        priority: Priority.HIGH,
        user_id: 2,
    },
    {
        title: 'Fix leaking faucet',
        description: 'Kitchen sink',
        completed: false,
        priority: Priority.HIGH,
        user_id: 2,
    },
    {
        title: 'Read TypeORM docs',
        description: 'Relations and migrations',
        completed: false,
        priority: Priority.LOW,
        user_id: 3,
    },
    {
        title: 'Build side project',
        description: 'Tasks notes app frontend',
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 3,
    },
    {
        title: 'Write unit tests',
        description: 'Auth and tasks modules',
        completed: true,
        priority: Priority.HIGH,
        user_id: 3,
    },
    {
        title: 'Organize desk',
        description: undefined,
        completed: true,
        priority: Priority.LOW,
        user_id: 4,
    },
    {
        title: 'Prepare presentation',
        description: 'Demo for stakeholders',
        completed: false,
        priority: Priority.HIGH,
        user_id: 4,
    },
    {
        title: 'Backup laptop',
        description: 'External drive sync',
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 4,
    },
    {
        title: 'Buy a new phone',
        description: 'iPhone 15 Pro',
        completed: false,
        priority: Priority.HIGH,
        user_id: 4,
        },
    {
        title: 'Book a flight',
        description: 'London to Paris',
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 4,
    },
    {
        title: 'Clean the house',
        description: 'Vacuum and dust',
        completed: false,
        priority: Priority.LOW,
        user_id: 4,
    },
    {
        title: 'Prepare for interview',
        description: 'Review company info',
        completed: false,
        priority: Priority.HIGH,
        user_id: 4,
    },
    {
        title: 'Buy a new car',
        description: 'Toyota Camry',
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 4,
    },
    {
        title: 'Organize the garage',
        description: 'Clean and organize tools',
        completed: false,
        priority: Priority.LOW,
        user_id: 4,
    },
    {
        title: 'Fix the leaky faucet',
        description: 'Kitchen sink',
        completed: false,
        priority: Priority.HIGH,
        user_id: 3,
    },
    {
        title: 'Build a new website',
        description: 'My portfolio',
        completed: false,
        priority: Priority.MEDIUM,
        user_id: 2,
    },
];
